/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package web_marketing_massivo_menu_e_submenu;

import br.com.jmary.home.Home;
import br.com.jmary.utilidades.Exportando;
import br.com.jmary.utilidades.PopupMenu_Colar;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import java.awt.Dimension;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.math.BigDecimal;
import java.net.URI;
import java.net.URL;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.net.ssl.HttpsURLConnection;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import web_marketing_massivo_browser_swt.MouseCorEPosicao;
import web_marketing_massivo_browser_swt.Codigo_Fonte_E_Script;

/**
 *
 * @author ana
 */
public class Web_Marketing_Massivo_Submenu_01 extends javax.swing.JPanel {

    public BigDecimal bigDecimal = new BigDecimal(0);
    String str_bigDecimal;
    
    Home Home;
        
    public Web_Marketing_Massivo_Submenu_01( Home Home2 ) {
        Home = Home2;
        str_bigDecimal = String.valueOf( bigDecimal );
        
        initComponents();
        
        inicio();
    }
    
    private void inicio(){
        
        /////////////////////////////////////////////////////////////////////
        new Thread() {   @Override public void run() { try { Thread.sleep(2000);
                        
            /////////////////////////////////////////////////////////////////////
            px_btAuto = btAuto.getX();
            py_btAuto = btAuto.getY();
                    
            px_mouse = px_btAuto + ( 1 * btAuto.getWidth() );
            py_mouse = py_btAuto + 530;                    
            /////////////////////////////////////////////////////////////////////                
                                                                                                                        
        } catch( Exception e ){ } } }.start();                  
        /////////////////////////////////////////////////////////////////////        
    }
    
    boolean boo_umavezbigDecimal = false;
    private void umavezbigDecimal(){
        
        /////////////////////////////////////////////////////////////////////
        /*new Thread() {   @Override public void run() {*/ try { Thread.sleep(2000);
            if( boo_umavezbigDecimal == false ){     
                boo_umavezbigDecimal = true;
                
                int x = Integer.parseInt( tf_ID.getText().trim() );
                bigDecimal = new BigDecimal(x);              
                str_bigDecimal = String.valueOf( bigDecimal );     
            }
        } catch( Exception e ){ } //} }.start();                  
        /////////////////////////////////////////////////////////////////////        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPOpcao_27 = new javax.swing.JPanel();
        tf_Endereco = new javax.swing.JTextField();
        JPOpcao_26 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_Posicao_X = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_Posicao_Y = new javax.swing.JTextField();
        JPOpcao_28 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        JPOpcao_29 = new javax.swing.JPanel();
        tf_Endereco_link_do_marketing = new javax.swing.JTextField();
        btAuto = new javax.swing.JButton();
        btAuto1 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        bt_Web_Marketing = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tf_ID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_Nome = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_Endereco_User = new javax.swing.JTextField();
        rbAuto = new javax.swing.JRadioButton();
        btFonte = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btAuto2 = new javax.swing.JButton();

        JPOpcao_27.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_27.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_27MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_27MousePressed(evt);
            }
        });

        tf_Endereco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_Endereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_Endereco.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_Endereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_EnderecoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_EnderecoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_EnderecoMouseExited(evt);
            }
        });
        tf_Endereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_EnderecoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_27Layout = new javax.swing.GroupLayout(JPOpcao_27);
        JPOpcao_27.setLayout(JPOpcao_27Layout);
        JPOpcao_27Layout.setHorizontalGroup(
            JPOpcao_27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_Endereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_27Layout.setVerticalGroup(
            JPOpcao_27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_27Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPOpcao_26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_26.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_26MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_26MousePressed(evt);
            }
        });

        jLabel80.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel80.setText("Link do Marketing: ");

        javax.swing.GroupLayout JPOpcao_26Layout = new javax.swing.GroupLayout(JPOpcao_26);
        JPOpcao_26.setLayout(JPOpcao_26Layout);
        JPOpcao_26Layout.setHorizontalGroup(
            JPOpcao_26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        JPOpcao_26Layout.setVerticalGroup(
            JPOpcao_26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Mensagem: ");

        jLabel7.setText("Posição X: ");

        tf_Posicao_X.setText("819");

        jLabel8.setText("Posição Y: ");

        tf_Posicao_Y.setText("578");

        JPOpcao_28.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_28.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_28MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_28MousePressed(evt);
            }
        });

        jLabel81.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel81.setText("Link do Marketing: ");

        javax.swing.GroupLayout JPOpcao_28Layout = new javax.swing.GroupLayout(JPOpcao_28);
        JPOpcao_28.setLayout(JPOpcao_28Layout);
        JPOpcao_28Layout.setHorizontalGroup(
            JPOpcao_28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel81, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        JPOpcao_28Layout.setVerticalGroup(
            JPOpcao_28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        JPOpcao_29.setBackground(new java.awt.Color(255, 255, 255));
        JPOpcao_29.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 153)));
        JPOpcao_29.setPreferredSize(new java.awt.Dimension(284, 27));
        JPOpcao_29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPOpcao_29MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPOpcao_29MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPOpcao_29MousePressed(evt);
            }
        });

        tf_Endereco_link_do_marketing.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tf_Endereco_link_do_marketing.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_Endereco_link_do_marketing.setText("*** Olá, Tudo Bem? Quero lhe Convidar Para Curtir Minha Página No facebook *** https://www.facebook.com/PerguntasERespostasJMary/photos/a.1597447833682895.1073741862.448800718547618/1664413850319626/?type=3&theater");
        tf_Endereco_link_do_marketing.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tf_Endereco_link_do_marketing.setPreferredSize(new java.awt.Dimension(209, 25));
        tf_Endereco_link_do_marketing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_Endereco_link_do_marketingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tf_Endereco_link_do_marketingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_Endereco_link_do_marketingMouseExited(evt);
            }
        });
        tf_Endereco_link_do_marketing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_Endereco_link_do_marketingKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout JPOpcao_29Layout = new javax.swing.GroupLayout(JPOpcao_29);
        JPOpcao_29.setLayout(JPOpcao_29Layout);
        JPOpcao_29Layout.setHorizontalGroup(
            JPOpcao_29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPOpcao_29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_Endereco_link_do_marketing, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPOpcao_29Layout.setVerticalGroup(
            JPOpcao_29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPOpcao_29Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tf_Endereco_link_do_marketing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btAuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/nuvem.png"))); // NOI18N
        btAuto.setToolTipText("Auto Total");
        btAuto.setBorder(null);
        btAuto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAutoMousePressed(evt);
            }
        });

        btAuto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/som.png"))); // NOI18N
        btAuto1.setToolTipText("Mouse");
        btAuto1.setBorder(null);
        btAuto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAuto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAuto1MousePressed(evt);
            }
        });

        jToolBar2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setPreferredSize(new java.awt.Dimension(658, 71));

        jSeparator11.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator11);

        bt_Web_Marketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/Estrtutura_de_Dados.png"))); // NOI18N
        bt_Web_Marketing.setText("Web Marketing Facebook Auto");
        bt_Web_Marketing.setFocusable(false);
        bt_Web_Marketing.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_Web_Marketing.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_Web_Marketing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_Web_MarketingMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_Web_MarketingMousePressed(evt);
            }
        });
        jToolBar2.add(bt_Web_Marketing);

        jSeparator8.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator8);

        jButton1.setText(" INICIAR MARKETING SEM O BANCO DE DADOS ");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jButton2.setText("INICIAR MARKETING COM O BANCO DE DADOS ");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jButton3.setText("INICIAR PREENCHIMENTO - BANCO DE DADOS ");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        jLabel9.setText("ID: ");

        tf_ID.setText("437");

        jLabel10.setText("Nome: ");

        tf_Nome.setEditable(false);
        tf_Nome.setEnabled(false);

        jLabel11.setText("Endereço: ");

        tf_Endereco_User.setEditable(false);
        tf_Endereco_User.setEnabled(false);

        rbAuto.setSelected(true);
        rbAuto.setText("Auto");
        rbAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbAutoMousePressed(evt);
            }
        });

        btFonte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/ip_conexao.png"))); // NOI18N
        btFonte.setToolTipText("Auto Total");
        btFonte.setBorder(null);
        btFonte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFonte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btFonteMousePressed(evt);
            }
        });

        jLabel12.setText("Fonte:");

        btAuto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_controle_menus_norte/imagens/sql.png"))); // NOI18N
        btAuto2.setToolTipText("Mouse");
        btAuto2.setBorder(null);
        btAuto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAuto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAuto2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JPOpcao_28, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPOpcao_29, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(rbAuto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Posicao_X, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAuto2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Posicao_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAuto1)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_Endereco_User)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFonte, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf_Posicao_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(tf_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(tf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12))
                            .addComponent(btFonte, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAuto2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAuto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tf_Posicao_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_Endereco_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addComponent(rbAuto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JPOpcao_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JPOpcao_29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
     
    private void bt_Web_MarketingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Web_MarketingMousePressed
        if( jButton1.getText().trim().equals( "INICIAR MARKETING SEM O BANCO DE DADOS" ) ){
            
            try{
                Home.ControleTabs.removerTabSelecionado();
                Thread.sleep( 1000 );
            } catch( Exception e ){}
                        
            boo_iniciar_Marketing_Sem_O_Banco_de_Dados = true;
            iniciar_Marketing_Sem_O_Banco_de_Dados(); 
            jButton1.setText("PARAR MARKETING SEM O BANCO DE DADOS");
        }
        else if( jButton1.getText().trim().equals( "PARAR MARKETING SEM O BANCO DE DADOS" ) ){
            
            boo_iniciar_Marketing_Sem_O_Banco_de_Dados = false;
            jButton1.setText("INICIAR MARKETING SEM O BANCO DE DADOS");
        }
    }//GEN-LAST:event_bt_Web_MarketingMousePressed

    private void bt_Web_MarketingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Web_MarketingMouseEntered
        Home.tocarSon.tocar( 51 );
    }//GEN-LAST:event_bt_Web_MarketingMouseEntered

    private void JPOpcao_26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MouseEntered

    private void JPOpcao_26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MouseExited

    private void JPOpcao_26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_26MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_26MousePressed

    PopupMenu_Colar PopupMenu_Colar;
    private void tf_EnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EnderecoMouseClicked
        try{
            PopupMenu_Colar = new PopupMenu_Colar(tf_Endereco);
        } catch( Exception e ){}
    }//GEN-LAST:event_tf_EnderecoMouseClicked

    private void tf_EnderecoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EnderecoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EnderecoMouseEntered

    private void tf_EnderecoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_EnderecoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EnderecoMouseExited

    private void tf_EnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_EnderecoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_EnderecoKeyReleased

    private void JPOpcao_27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MouseEntered

    private void JPOpcao_27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MouseExited

    private void JPOpcao_27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_27MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_27MousePressed

    private void JPOpcao_28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_28MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_28MouseEntered

    private void JPOpcao_28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_28MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_28MouseExited

    private void JPOpcao_28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_28MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_28MousePressed

    private void tf_Endereco_link_do_marketingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco_link_do_marketingMouseClicked
        try{
            PopupMenu_Colar = new PopupMenu_Colar(tf_Endereco);
        } catch( Exception e ){}
    }//GEN-LAST:event_tf_Endereco_link_do_marketingMouseClicked

    private void tf_Endereco_link_do_marketingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco_link_do_marketingMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco_link_do_marketingMouseEntered

    private void tf_Endereco_link_do_marketingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Endereco_link_do_marketingMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco_link_do_marketingMouseExited

    private void tf_Endereco_link_do_marketingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_Endereco_link_do_marketingKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_Endereco_link_do_marketingKeyReleased

    private void JPOpcao_29MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_29MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_29MouseEntered

    private void JPOpcao_29MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_29MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_29MouseExited

    private void JPOpcao_29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPOpcao_29MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPOpcao_29MousePressed

    private void btAutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAutoMousePressed
        
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                
                int x = Integer.parseInt( tf_ID.getText().trim() );
                bigDecimal = new BigDecimal(x);              
                str_bigDecimal = String.valueOf( bigDecimal );
                
                webBrowser = new JWebBrowser(); // new JWebBrowser( JWebBrowser.useXULRunnerRuntime() );
                webBrowser.navigate( "https://www.facebook.com/profile.php?id=" + str_bigDecimal );
                Home.adicionar_Tela_De_Trabalho("Web Marketing Facebook", webBrowser );
            }
          }); 
    }//GEN-LAST:event_btAutoMousePressed

    private void btAuto1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAuto1MousePressed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MouseCorEPosicao MouseCorEPosicao = new MouseCorEPosicao();
                MouseCorEPosicao.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                MouseCorEPosicao.setVisible(true);
            }
        });
    }//GEN-LAST:event_btAuto1MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
                 
        if( jButton1.getText().trim().equals( "INICIAR MARKETING SEM O BANCO DE DADOS" ) ){
            
            boo_iniciar_Marketing_Sem_O_Banco_de_Dados = true;
            iniciar_Marketing_Sem_O_Banco_de_Dados(); 
            jButton1.setText("PARAR MARKETING SEM O BANCO DE DADOS");
        }
        else if( jButton1.getText().trim().equals( "PARAR MARKETING SEM O BANCO DE DADOS" ) ){
            
            boo_iniciar_Marketing_Sem_O_Banco_de_Dados = false;
            jButton1.setText("INICIAR MARKETING SEM O BANCO DE DADOS");
        }
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        
        if( jButton3.getText().trim().equals( "INICIAR PREENCHIMENTO - BANCO DE DADOS" ) ){
            
            //boo_iniciar_Preenchimento_Do_Banco_de_Dados = true;
            //iniciar_Preenchimento_Do_Banco_de_Dados();
            jButton3.setText("PARAR PREENCHIMENTO - BANCO DE DADOS");
        }
        else if( jButton3.getText().trim().equals( "PARAR PREENCHIMENTO - BANCO DE DADOS" ) ){
            
            //boo_iniciar_Preenchimento_Do_Banco_de_Dados = false;
            jButton3.setText("INICIAR PREENCHIMENTO - BANCO DE DADOS");
        }
    }//GEN-LAST:event_jButton3MousePressed

    private void btFonteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFonteMousePressed
        try{                
            String codigo_Fonte = webBrowser.getHTMLContent();                
            String newFonte2 = codigo_Fonte.replaceAll( 
                    ">", 
                    "> \n"
            );
            
            //JTextArea jTextArea_01 = new javax.swing.JTextArea();
            //jTextArea_01.setText( newFonte2 );   
            
            Home.adicionar_Tela_De_Trabalho("Script", new Codigo_Fonte_E_Script( webBrowser, newFonte2 ) );
            //Home.adicionar_Tela_De_Trabalho( "Codigo Fonte", jTextArea_01 );
        }catch( Exception ec ){ ec.printStackTrace(); } 
    }//GEN-LAST:event_btFonteMousePressed

    private void rbAutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAutoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAutoMousePressed

    private void btAuto2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAuto2MousePressed
        Home.adicionar_Tela_De_Trabalho("Script", new Codigo_Fonte_E_Script( webBrowser ) );
    }//GEN-LAST:event_btAuto2MousePressed
    
    Exportando Exportando;
    JWebBrowser webBrowser;;
    int x;
    int y;
    String endereco_link_do_marketing;
    int px_mouse;
    int py_mouse;
    int px_btAuto;
    int py_btAuto;
    boolean boo_iniciar_Marketing_Sem_O_Banco_de_Dados = true;
    //NÍVEL 1 - OBTENDO USUÁRIO VÁLIDO
    private void iniciar_Marketing_Sem_O_Banco_de_Dados() { 
        
        umavezbigDecimal();
        
        try { Thread.sleep( 10 );
                            
            Exportando = new Exportando("OBTENDO USUÁRIO VÁLIDO...");
            Exportando.setVisible(true);Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( 100 );
            Exportando.pbg.setValue( 50 ); 

            BigDecimal resultado = bigDecimal.add(new BigDecimal(1));
            bigDecimal = resultado;
            str_bigDecimal = String.valueOf( bigDecimal );
            
            String str_url = "https://www.facebook.com/profile.php?id=" + str_bigDecimal;
                
            URL url = new URL( str_url );
            
            StringBuilder recepcao_anterior = new StringBuilder(); 
            StringBuilder recepcao_proxima = new StringBuilder(); 
            HttpsURLConnection conexao = (HttpsURLConnection) url.openConnection();
            BufferedReader obterCodigoFonte = new BufferedReader( new InputStreamReader( conexao.getInputStream() ) ); 
                           
            int contador = 0;
            int letra;
            while ( ( (letra = obterCodigoFonte.read()) != -1) ){
                
                String letraStr = String.valueOf( (char) letra );                
                
                contador++;
                if( contador < 7524 ){
                    
                    if( letraStr.equalsIgnoreCase(">") ){
                    
                        recepcao_anterior.append( letraStr );                    
                        recepcao_anterior.append( "\n" );
                    }
                    else{
                        recepcao_anterior.append( letraStr );  
                    }
                }
                else if( contador < 9000 ){  //  else if( contador > 7524 ){
                    
                    if( letraStr.equalsIgnoreCase(">") ){
                    
                        recepcao_proxima.append( letraStr );                    
                        recepcao_proxima.append( "\n" );
                    }      
                    else{
                        recepcao_proxima.append( letraStr );    
                    }
                    //break;
                }
            }  
                                                  
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////             
            tf_ID.setText( str_bigDecimal );
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  

            Exportando.fechar();   
            
            //JTextArea jTextArea_01 = new javax.swing.JTextArea();
            //jTextArea_01.append(recepcao_proxima.toString()); 
            //Home.adicionar_Tela_De_Trabalho( str_bigDecimal, jTextArea_01 ); 
            
            /*
            try{
                Arquivo_Ou_Pasta.criarPasta( System.getProperty("user.dir"), "fontes" );                        
                Arquivo_Ou_Pasta.criar_Arquivo_Iso_Boo_Tipo_UTFISO( 
                System.getProperty("user.dir") + "\\" + "fontes" + "\\" + str_bigDecimal + ".html", jTextArea_01.getText() , "UTF-8" );
            } catch (Exception e) { e.printStackTrace(); }
            */
            
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
        try{           
                    
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    x = Integer.parseInt( tf_Posicao_X.getText().trim() );
                    y = Integer.parseInt( tf_Posicao_Y.getText().trim() );
                    endereco_link_do_marketing = tf_Endereco_link_do_marketing.getText().trim();
                    
                    Map<String, List<String>> headers = new LinkedHashMap<String, List<String>>();
                    headers.put("Set-Cookie", Arrays.asList( "c_user=4" ) );
                    URI uri = URI.create( "https://www.facebook.com/profile.php?id=" + str_bigDecimal );
                    try{ java.net.CookieHandler.getDefault().put(uri, headers); } catch( Exception e ){ } 
                    
                    webBrowser = new JWebBrowser(); // new JWebBrowser( JWebBrowser.useXULRunnerRuntime() );
                    webBrowser.navigate( "https://www.facebook.com/profile.php?id=" + str_bigDecimal );
                                                          
                    try{
                        Thread.sleep(10);
                        Toolkit tk = Toolkit.getDefaultToolkit();
                        Dimension d = tk.getScreenSize();
                        webBrowser.setMaximumSize( d );
                        webBrowser.setSize(d);
                        webBrowser.setPreferredSize(d);
                        Home.adicionar_Tela_De_Trabalho("Web Marketing Facebook", webBrowser );
                    } catch( Exception e ){ }                   
                                        
                    /////////////////////////////////////////////////////////////////////
                    new Thread() {   @Override public void run() { try { Thread.sleep(10000);
                        
                        Robot r = null;
                        r = new Robot();
                               
                        // ABRIR MENSAGEM
                        r.mouseMove( px_mouse, py_mouse );  
                        r.mousePress(InputEvent.BUTTON1_MASK);  
                        r.mouseRelease(InputEvent.BUTTON1_MASK);
                        
                        // ABRIR MENSAGEM
                        /*
                        int py2 = py_mouse - 90;
                        r.mouseMove( px_mouse, py2 );  
                        r.mousePress(InputEvent.BUTTON1_MASK);  
                        r.mouseRelease(InputEvent.BUTTON1_MASK);
                        */
                        
                        //clipboard.setContents
                        StringSelection selection = new StringSelection( tf_Endereco_link_do_marketing.getText().trim() );
                        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                        clipboard.setContents(selection, selection);
                        
                        // COLAR MARKETING
                        Thread.sleep(4000);
                        r.keyPress(KeyEvent.VK_CONTROL);
                        r.keyPress(KeyEvent.VK_V);
 
                        r.keyRelease(KeyEvent.VK_V);
                        r.keyRelease(KeyEvent.VK_CONTROL);
                        
                        Thread.sleep(4000);
                        r.keyPress(KeyEvent.VK_ENTER);
                        r.keyRelease(KeyEvent.VK_ENTER);
                        
                        
                        // SAIR DA MENSAGEM
                        Thread.sleep(6000);
                        r.keyPress(KeyEvent.VK_ESCAPE);
                        r.keyRelease(KeyEvent.VK_ESCAPE);
                        
                        // CONFIRMAR SAIR DA MENSAGEM
                        Thread.sleep(1000);
                        r.keyPress(KeyEvent.VK_ENTER);
                        r.keyRelease(KeyEvent.VK_ENTER);
                                                                                                                        
                        Thread.sleep(1000);
                        r.mouseMove( 100, 100 );  
                        r.mousePress(InputEvent.BUTTON1_MASK);  
                        r.mouseRelease(InputEvent.BUTTON1_MASK);
                        
                        if( rbAuto.isSelected() == true ){
                            Thread.sleep(1000);
                            r.mouseMove( 100, 100 );  
                            r.mousePress(InputEvent.BUTTON1_MASK);  
                            r.mouseRelease(InputEvent.BUTTON1_MASK);
                        }
                                                                                                                        
                    } catch( Exception e ){ } } }.start();                  
                    /////////////////////////////////////////////////////////////////////
                }
            });       
        
        } catch( Exception e ){}
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  
            
        }catch( Exception e ){      
            Exportando.fechar();
            //e.printStackTrace();
            
            if( boo_iniciar_Marketing_Sem_O_Banco_de_Dados == true ){
                try{
                    SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                        
                            iniciar_Marketing_Sem_O_Banco_de_Dados();
                        }
                    });  
                } catch( Exception es ){}
            }
        } 
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPOpcao_26;
    private javax.swing.JPanel JPOpcao_27;
    private javax.swing.JPanel JPOpcao_28;
    private javax.swing.JPanel JPOpcao_29;
    public javax.swing.JButton btAuto;
    public javax.swing.JButton btAuto1;
    public javax.swing.JButton btAuto2;
    public javax.swing.JButton btFonte;
    public javax.swing.JButton bt_Web_Marketing;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JRadioButton rbAuto;
    public javax.swing.JTextField tf_Endereco;
    public javax.swing.JTextField tf_Endereco_User;
    public javax.swing.JTextField tf_Endereco_link_do_marketing;
    public javax.swing.JTextField tf_ID;
    public javax.swing.JTextField tf_Nome;
    public javax.swing.JTextField tf_Posicao_X;
    public javax.swing.JTextField tf_Posicao_Y;
    // End of variables declaration//GEN-END:variables
}
